# Generated by Django 6.0.5 on 2026-05-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemoLead',
            new_name='Lead',
        ),
    ]
